from utilities import WordType, WordNote, PronNote, BookPage, Level, Item, process_dictionary, find_random_answers, \
    start_tests, Gender, generic_run_me

enota = {}

enota["unidade 2"] = (
    ("família", "famiglia"),
    ("pai", "padre"),
    ("mãe", "madre"),
    ("pais", "genitori"),
    ("crianças", "bambini"),
    ("filho", "figlio"),
    ("filha", "figlia"),
    ("irmão", "fratello"),
    ("irmã", "sorella"),
    ("avô", "nonno"),
    ("avó", "nonna"),
    ("neto", "nipote"),
    ("neta", "nipotina"),
    ("marido", "marito"),
    ("esposa", "moglie"),
    ("namorado", "ragazzo"),
    ("namorada", "ragazza"),
    ("parceiro", "partner (m)"),
    ("parceira", "partner (f)"),
    ("amigo", "amico"),
    ("amiga", "amica"),
    ("casado", "sposato"),
    ("separado", "separato"),
    ("amigos", "amici"),
    ("escola", "scuola"),
    ("creche", "asilo"),
    ("faculdade", "facoltà"),
    ("verbos", "verbi"),
    ("trabalhar", "lavorare"),
    ("ser", "essere"),
    ("falar", "parlare"),
    ("caminhar", "camminare"),
    ("ter", "avere"),
    ("de quem é?", "di chi è?", WordType.PRONOUN),
    ("quem?", "chi?", WordType.PRONOUN),
    ("de quem é esta bolsa?", "di chi è questa borsa?", WordType.PRONOUN),
    ("quem é este?", "chi è questo?", WordType.PRONOUN),
    ("este é meu pai", "questo è mio padre"),
    ("esta é minha mãe", "questa è mia madre"),
    ("este é meu filho", "questo è mio figlio"),
    ("esta é minha filha", "questa è mia figlia"),
    ("este é meu irmão", "questo è mio fratello"),
    ("esta é minha irmã", "questa è mia sorella"),
    ("este é meu avô", "questo è mio nonno"),
    ("esta é minha avó", "questa è mia nonna"),
    ("este é meu neto", "questo è mio nipote"),
    ("esta é minha neta", "questa è mia nipote"),
    ("este é meu marido", "questo è mio marito"),
    ("esta é minha esposa", "questa è mia moglie"),
    ("este é meu namorado", "questo è il mio ragazzo"),
    ("esta é minha namorada", "questa è la mia ragazza"),
    ("este é meu parceiro", "questo è il mio partner"),
    ("esta é minha parceira", "questa è la mia partner"),
    ("este é meu amigo", "questo è il mio amico"),
    ("esta é minha amiga", "questa è la mia amica"),
    ("meu", "mio"),
    ("seu", "il tuo"),
    ("seu (de vocês)", "il vostro"),
    ("pois não?", "desidera, prego?"),
    ("bom apetite", "buon appetito"),
    ("parabéns!", "congratulazioni!"),
    ("ai, desculpe", "ahi, mi scusi"),
    ("obrigado igualmente", "grazie anche a te"),
    ("tudo bem", "va bene"),
    ("desculpe, você pode repetir?", "scusa, puoi ripetere?"),
    ("desculpe, não entendo", "scusa, non capisco"),
    ("saúde!", "saluti!"),
    ("como ele é?", "com'è?"),
    ("como ela é?", "com'è?"),
    ("como eles são?", "com'è?"),
    ("como elas são?", "com'è?"),
    ("como é seu pai?", "com'è tuo padre?"),
    ("como é sua mãe?", "com'è tua madre?"),
    ("como é seu filho?", "com'è tuo figlio?"),
    ("como é sua filha?", "com'è tua figlia?"),
    ("como é seu irmão?", "com'è tuo fratello?"),
    ("como é sua irmã?", "com'è tua sorella?"),
    ("como é seu avô?", "com'è tuo nonno?"),
    ("como é sua avó?", "com'è tua nonna?"),
    ("como é seu neto?", "com'è tuo nipote?"),
    ("como é sua neta?", "com'è tua nipote?"),
    ("como é seu marido?", "com'è tuo marito?"),
    ("como é sua esposa?", "com'è tua moglie?"),
    ("como é seu namorado?", "com'è il tuo ragazzo?"),
    ("como é sua namorada?", "com'è la tua ragazza?"),
    ("que tipo", "che tipo"),
    ("jovem", "giovane"),
    ("velho", "vecchio"),
    ("magro", "asciutto/magro"),
    ("gordo", "di spessore/grasso/obeso"),
    ("pequeno", "piccolo"),
    ("alto", "alto"),
    ("bonito", "bello"),
    ("feio", "brutto"),
    ("bebida", "bevanda"),
    ("água", "acqua"),
    ("água mineral", "acqua minerale"),
    ("café", "caffè"),
    ("chá", "thè"),
    ("limonada", "limonata"),
    ("cerveja", "birra"),
    ("vinho branco", "vino bianco"),
    ("vinho tinto", "vino rosso"),
    ("de onde é a família Martinez?", "da dove viene la famiglia Martinez?"),
    ("quantos anos tem o pai?", "quanti anni ha il padre?"),
    ("a mãe trabalha agora?", "ma la mamma lavora adesso?"),
    ("qual é a profissão do pai?", "cosa fa di mestiere il padre?"),
    ("o que a filha estuda?", "cosa sta studiando la figlia?"),
    ("meu irmão", "mio fratello"),
    ("seu irmão", "tuo fratello"),
    ("minha irmã", "mia sorella"),
    ("sua irmã", "tua sorella"),
    ("esta é minha família", "questa è la mia famiglia"),
    ("este é seu pai?", "questo è tuo padre?"),
    ("não, este é meu irmão", "no questo è mio fratello"),
    ("esta é sua irmã?", "questa è tua sorella?"),
    ("não, esta é minha esposa", "no, questa è mia moglie"),
    ("claro", "ovviamente"),
    ("este é seu telefone?", "è questo il tuo telefono?"),
    ("sim, este é meu telefone", "si, questo è il mio telefono"),
    ("não, este não é meu telefone", "no, questo non è il mio telefono"),
    ("bolsa", "borsa/sacchetto"),
    ("de quem é o cigarro?", "di chi è la sigaretta?"),
    ("de quem são as bolsas?", "di chi sono le borse?"),
    ("livro", "libro", Gender.MALE),
    ("lápis", "matita (penna)"),
    ("caderno", "quaderno"),
    ("relógio", "orologio/ora"),
    ("vamos tomar um café", "andiamo a prendere un caffè"),
    ("caneta esferográfica", "matita chimica (biro)"),
    ("vamos comer uma pizza", "andiamo a prendere una pizza"),
    ("de quem é o celular?", "di chi è il cellulare?", Gender.MALE),
    ("de quem é o livro?", "di chi è il libro?", Gender.MALE),
    ("de quem é a pizza?", "di chi è la pizza?", Gender.FEMALE),
    ("de quem é a cerveja?", "di chi è la birra", Gender.FEMALE),
    ("cerveja", "birra", Gender.FEMALE),
    ("o celular do irmão", "il cellulare del fratello"),
    ("o que é isso?", "cosa è questo?"),
    ("este é um telefone velho", "questo è un vecchio telefono"),
    ("estes são telefones velhos", "questi sono vecchi telefoni"),
    ("este é o livro", "questo è il libro"),
    ("minha irmã é pequena e não é magra", "mia sorella è piccola e non magra"),
    ("caneta", "penna"),
    ("estes são celulares", "questi sono telefoni"),
    ("estes são livros", "questi sono libri"),
    ("estes são os italianos", "questi sono gli italiani"),
    ("estou na Itália", "sono in Italia"),
    ("estes são os italianos?", "questi sono gli italiani?"),
    ("agora", "adesso"),
    ("pequena", "piccola"),
    ("magra", "magra"),
    ("jovem (f)", "giovane (f)"),
    ("bonita", "bella"),
    ("velha", "vecchia"),
    ("feia", "brutta"),
    ("grande (f)", "grande (f)"),
    ("gorda", "grassa"),
    ("esta é minha cerveja", "questa è la mia birra", Gender.FEMALE),
    ("este é meu vinho", "questo è il mio vino", Gender.MALE),
    ("este é meu leite", "questo è il mio latte", Gender.MALE),
    ("ele trabalha muito", "lui lavora molto"),
    ("eu tenho cabelos pretos", "io ho i capelli neri"),
    ("meu irmão é grande e gordo", "mio fratello è grande e grasso"),
    ("meu pai é velho e grande", "mio padre è vecchio e grande"),
    ("minha amiga", "la mia amica"),
    ("meu amigo", "il mio amico"),
    ("ele é sempre alegre", "è sempre allegro"),
    ("ela é sempre alegre", "lei è sempre allegra"),
    ("ele é sempre alegre", "lui è sempre allegro"),
    ("sempre", "sempre"),
    ("alegre", "allegro"),
    ("ele é muito amigável", "è molto amichevole"),
    ("amigável", "amichevole"),
    ("ela é bonita e magra", "lei è lepa e magra"),
    ("ele tem 46 anos", "ha 46 anni"),
    ("o marido tem 46 anos", "il marito ha 46 anni"),
    ("o filho é estudante universitário", "il figlio studia all'università"),
    ("a filha é pequena e magra", "la figlia è piccola e magra"),
    ("a filha é grande e magra", "la figlia è grande e magra"),
    ("a filha é grande e gorda", "la figlia è grande e grassa"),
    ("ela tem cabelos grisalhos e olhos azuis", "lei hai capelli grigi e gli occhi azzurri"),
    ("ele tem cabelos castanhos e olhos cinzas", "lui ha i capelli castani e gli occhi grigi"),
    ("ele tem cabelos grisalhos e olhos castanhos", "lui hai capelli grigi e gli occhi castani"),
    ("ela tem cabelos castanhos e olhos azuis", "lei ha i capelli castani e gli occhi azzurri"),
    ("ela tem cabelos castanhos e olhos castanhos", "lei ha i capelli castani e gli occhi castani"),
    ("ele tem cabelos ruivos e olhos azuis", "ha i capelli rossi e gli occhi azzurri"),
    ("ela tem cabelos loiros e olhos azuis", "lei ha i capelli biondi e gli occhi azzurri"),
    ("ele tem cabelos castanhos e olhos azuis", "ha i capelli castani e gli occhi azzurri"),
    ("ela tem cabelos loiros e olhos cinzas", "lei ha i capelli biondi e gli occhi grigi"),
    ("ela tem cabelos longos", "lei ha i capelli lunghi"),
    ("ela tem cabelos curtos", "lei ha i capelli corti"),
    ("ela tem cabelos castanhos", "lei ha i capelli castani"),
    ("ela tem cabelos loiros", "lei ha i capelli biondi"),
    ("ela tem cabelos pretos", "lei ha i capelli neri"),
    ("ela tem cabelos grisalhos", "lei ha i capelli grigi"),
    ("ela tem cabelos ruivos", "lei ha i capelli rossi"),
    ("ele tem olhos grandes", "ha occhi grandi"),
    ("ele tem olhos pequenos", "ha occhi piccoli"),
    ("ele tem olhos castanhos", "ha occhi castani"),
    ("ele tem olhos azuis", "ha occhi azzurri"),
    ("ele tem olhos verdes", "ha occhi verdi"),
    ("ele tem olhos cinzas", "ha occhi grigi"),
    ("ele tem olhos pretos", "ha occhi neri"),
)

if __name__ == "__main__":
    generic_run_me(enota)