from utilities import WordType, WordNote, PronNote, BookPage, Level, Item, process_dictionary, find_random_answers, \
    start_tests, Gender, WebLink, AudioLink, generic_run_me

enota = {}

enota["unidade 1 2023"] = (
    ("unidade", "unità"),
    ("pagar", ("pagare", "saldare", "liquidare"), WordType.VERB),
    ("eu pago", "io pago"),
    ("você paga", "tu paghi"),
    ("ele paga", "lui paga"),
    ("nós pagamos", "noi paghiamo"),
    ("vocês pagam", "voi pagate"),
    ("eles pagam", "loro pagano"),
    ("tenho que pagar o aluguel", "Devo pagare l'affitto"),
    ("tenho que pagar", "devo pagare"),
    ("eu devo / tenho que", "devo"),
    ("aluguel", "affitto", Gender.MALE),
    ("pagamento", "pagamento"),
    ("pagável", "pagabile"),
    ("dicionário", "dizionario", Gender.MALE),
    ("mundo", "mondo"),
    ("aconselhar", "consigliare", WordType.VERB),
    ("conselheiro", "consigliere"),
    ("notícias do dia", "notizie del giorno"),
    ("diário", "diario", Gender.MALE),
    ("vocês sabem?", "lo sapete?"),
    ("crise", "crisi", Gender.FEMALE),
    ("salário", "stipendio", Gender.MALE),
    ("o que", "cosa"),
    ("seu / de vocês", "vostro"),
    ("palavra", "parola"),
    ("texto", "testo"),
    ("se vocês perderam", "se avete perso"),
    ("não encontro as palavras", "Non trovo le parole"),
    ("eu encontro", "trovo"),
    ("encontrar", "trovare", WordType.VERB),
    ("você encontra", "trovi"),
    ("ele encontra", "lui trova"),
    ("nós encontramos", "troviamo"),
    ("vocês encontram", "trovate"),
    ("eles encontram", "trovano"),
    ("encontrar trabalho", "trovare lavoro"),
    ("notícia", ("notizia", "novità")),
    ("noticiário", "notiziario"),
    ("transmissão", "trasmissione"),

    ("carteira", "portafoglio", Gender.FEMALE),
    ("dinheiro", "denaro/soldi", Gender.MALE),
    ("cartão de crédito", "carta di credito", Gender.MALE),
    ("com licença, esta é a sua carteira?", "scusi, è il tuo portafoglio?"),
    ("tempestade", ("temporale", "tempesta"), Gender.FEMALE),
    ("temporal", "temporale", Gender.MALE),
    ("a tempestade causou mortos e desaparecidos", "la tempesta ha causato morti e dispersi"),
    ("causar", "causare", WordType.VERB),
    ("causou", "ha causato"),
    ("desaparecidos", "dispersi"),
    ("pessoa desaparecida", "persona dispersa"),
    ("pessoa", "persona"),
    ("sentir falta", ("mancare", "perdere", "sentire la mancanza"), WordType.VERB),
    ("sinto sua falta", "mi manchi"),
    ("sinto falta", "mi mancano"),
    ("fez falta", "mancato"),

    ("de nada", "non c'è di che"),
    ("aqui está / pois não", ("prego", "ecco")),
    ("o que vocês veem?", "cosa vedete?"),
    ("o que você vê?", "cosa vedi?"),
    ("o que eu vejo?", "cosa vedo?"),
    ("o que vocês veem agora?", "cosa vedete adesso?"),
    ("o que eu vejo agora?", "cosa vedo adesso?"),
    ("livro", "libro", Gender.MALE),
    ("você lê um livro", "tu leggi un libro"),
    ("ele lê um livro", "lui legge un libro"),

    ("Henrik vem da Finlândia", "Henrik viene dalla Finlandia"),
    ("ele é da Finlândia", "lui viene dalla finlandia"),
    ("ele vai morar um ano no Brasil", "Vivrà in Brasile per un anno"),
    ("o que o Martin disse?", "cosa ha detto Martin?"),

    ("disse", ("detto", "raccontato")),
    ("eu disse", "ho detto"),
    ("o que eu te disse?", "Cosa ti ho detto?"),
    ("dizer", "dire", WordType.VERB),

    ("isso é fácil de dizer", "è facile da dire"),
    ("isso é fácil", "è facile"),
    ("fácil", "facile"),

    ("alguém está chegando", "qualcuno sta arrivando"),
    ("alguém", "qualcuno"),
    ("chegar / vir", ("venire", "arrivare"), WordType.VERB),
    ("eu chego", "io arrivo"),
    ("você chega", "tu arrivi"),
    ("ele chega", "arriva"),

    ("vocês moram aqui agora?", "adesso abitate qui?"),
    ("onde vocês moram?", "dove abitate?"),
    ("onde vocês vivem?", "dove vivete?"),
    ("onde você vive?", "dove vivi?"),
    ("onde você mora agora?", "dove vivi adesso?"),
    ("onde", "dove"),
    ("moro aqui", "Abito qui"),
    ("vivo aqui", "Vivo qui"),
    ("moro aqui agora", "Vivo qui adesso"),

    ("agora", ("adesso", "ora")),
    ("eu sou a vizinha do primeiro andar", "io sono la vicina del primo piano"),
    ("eu sou o vizinho", "io sono il vicino"),
    ("de / do / da", "da / di"),

    ("primeiro", ("primo", "principale")),
    ("primeiro andar", "primo piano", Gender.MALE),
    ("cafeteria", ("caffetteria", "bar"), Gender.FEMALE),

    ("que tipo de / qual", ("quali", "che tipo di")),
    ("verbos", "verbi"),
    ("trabalhar", "lavorare", WordType.VERB),
    ("eu trabalho", "io lavoro"),
    ("andar / ir", "andare", WordType.VERB),
    ("eu vou", "io vado"),
    ("chamar-se", "chiamarsi", WordType.VERB),
    ("me chamo", "mi chiamo"),
    ("assinar", "firmare", WordType.VERB),
    ("eu assino", "io firmo"),
    ("precisar", "avere bisogno di", WordType.VERB),
    ("eu preciso", "io ho bisogno di"),
    ("nascer", "nascere", WordType.VERB),
    ("eu nasço", "io nasco"),
    ("conhecer", "conoscere", WordType.VERB),
    ("eu conheço", "io conosco"),
    ("encontro", ("incontro", "riunione", "convegno")),
    ("encontrar", "incontrare", WordType.VERB),
    ("eu encontro", "io incontro"),
    ("nós encontramos", "noi incontriamo"),
    ("vocês encontram", "voi incontrate"),
    ("eles encontram", "loro incontrano"),
    ("sorte", "fortuna"),
    ("morar", "abitare", WordType.VERB),
    ("eu moro", "io abito"),
    ("estudar", "studiare", WordType.VERB),
    ("eu estudo", "io studio"),
    ("viver", "vivere", WordType.VERB),
    ("ao vivo", "dal vivo"),
    ("eu vivo", "io vivo"),
    ("jovem", "giovane", WordType.ADJECTIVE),
    ("velho", "vecchio", WordType.ADJECTIVE),
    ("ocupado / empregado", ("impiegato", "occupato", "impegnato")),
    ("aposentado", "pensionato"),
    ("aposentada", "pensionata"),
    ("estudante", "studente/studentessa"),
    ("alto", "alto"),
    ("grande", "grande"),
    ("pequeno", "piccolo"),
    ("magro", "magro"),
    ("gordo", "grasso"),
    ("bonito", "bello"),
    ("bom", "buono"),
    ("simpático / gentil", "gentile"),
    ("grosseiro", "scortese"),
    ("olhos", "occhi"),
    ("cabelo", "capelli"),
    ("barba", "barba"),
    ("óculos", "occhiali"),
    ("nosso", ("nostro", "il nostro")),

    ("você quer", "tu vuoi"),
    ("o que você quer estudar?", "cosa vuoi studiare?"),
    ("ele estudou medicina", "ha studiato medicina"),
    ("nome", "nome"),
    ("sobrenome", "cognome"),
    ("senhor", "signore"),
    ("senhora", "signora"),
    ("gênero", "genere"),
    ("homem", "uomo"),
    ("mulher", "donna"),
    ("data de nascimento", "data di nascita"),
    ("local de nascimento", "luogo di nascita"),
    ("aniversário", "compleanno"),
    ("endereço", "indirizzo"),
    ("rua", "via"),
    ("número da casa", "numero civico"),
    ("código postal (CEP)", "codice postale"),
    ("lugar / local", ("posto", "luogo", "posizione")),
    ("cidade", "città"),
    ("país", "stato"),
    ("nacionalidade", "nazionalità"),
    ("profissão", "professione"),
    ("emprego / trabalho", "lavoro"),
    ("tesouro", ("tesoro", "gioiello")),

    ("que tipo de verbo é esse?", "che tipo di verbo è questo?"),
    ("identidade pessoal", "identità personale"),
    ("pessoal", "personale (singolare)"),
    ("pessoais", "personali (plurale)"),

    ("qual é a sua identidade pessoal?", "qual è la tua identità personale?"),
    ("vocabulário", "lessico"),
    ("família", "famiglia"),

    ("muito prazer", "piacere!"),
    ("você toca bateria?", ("suonate la batteria?", "ma suoni la batteria")),
    ("sabe, aqui às dez da noite há silêncio", "sapete, qui alle dieci di sera c'è silenzio"),
    ("aqui", "qui"),
    ("claro", ("certo", "ovviamente")),
    ("silêncio / paz", ("silenzio", "pace", "tranquillità")),
    ("é às dez", "è alle dieci"),
    ("à noite / de noite", "di sera"),
    ("às", "alle"),
    ("às dez", "alle dieci"),
    ("às dez da noite", "alle dieci di sera"),
    ("eu gosto de silêncio", "mi piace la tranquillità"),
    ("ela gosta", "a lei piace"),
    ("vocês sabem", "sapete"),
    ("que temos um vizinho novo", "(che) abbiamo un nuovo vicino"),
    ("Henrik toca bateria", "Henrik suona la batteria"),
    ("por que", ("perché", "per quale motivo", "per quale ragione")),
    ("por que ele toca bateria?", "perché suona la batteria?"),
    ("por que você toca bateria?", "perché suoni la batteria?"),
    ("por que você não me escuta?", "perché non mi ascolti?"),
    ("por que você me diz isso?", "perché mi dici questo?"),
    ("o Martin está aprendendo português", "martin sta imparando il portoghese"),
    ("ele está aprendendo", "sta imparando"),
    ("falar", "parlare"),
    ("conversar", "parlare (dialogare)"),
    ("resposta", "risposta"),
    ("responder", "rispondere"),
    ("quais línguas você fala?", "quali lingue parli?"),
    ("quais", "quali"),
    ("quais línguas", "quali lingue"),
    ("quais línguas você fala agora?", "quali lingue parli adesso?"),
    ("língua / idioma", ("lingua", "linguaggio", "idioma")),

    ("caderno de exercícios", "Quaderno di lavoro"),
    ("livro didático", "libro di testo"),
    ("criança", "bambino"),
    ("filho", "figlio"),
    ("filha", "figlia"),
    ("carteira de identidade", "carta d'identità"),
    ("passaporte", "passaporto"),
    ("formulário", "modulo"),
    ("casado", "sposato"),
    ("apresente-se", "presentarsi"),
    ("quem é este?", "chi è questo?"),
    ("este é o Martin", "questo è Martin"),
    ("com", "con"),
    ("o senhor é o nosso vizinho", "voi siete il nostro vicino"),
    ("vou morar aqui por um ano", "vivrò qui per un anno"),
    ("eu vou morar", "io vivrò (futuro)"),
    ("oi / olá", "ciao"),
    ("o senhor, por outro lado, não é", "voi invece non siete"),
    ("de onde o senhor é?", "da dove venite?"),
    ("e o que é isso?", "e cosa è questo?"),
    ("isso é uma bateria?", "questi sono tamburi?"),
    ("sério? / verdade?", ("davvero?", "veramente?")),
    ("toco bateria por hobby", "suono la batteria per hobby"),
    ("eu gosto de jazz", "mi piace il jazz"),
    ("você não gosta?", "non ti piace?"),
    ("posso ajudá-lo?", "posso aiutarvi?"),
    ("eu gosto", "mi piace"),
    ("no instituto trabalho como pesquisador", "all'istituto lavoro come ricercatore"),
    ("o senhor é muito gentil", "siete molto gentile"),
    ("muito", "molto"),
    ("para qual andar nós vamos?", "a quale piano andiamo?"),
    ("no corredor", "nel corridoio"),
    ("resposta", ("risposta", "soluzione", "replica")),
    ("para o segundo", "al secondo"),
    ("vocês vêm beber algo à noite?", "e venite a bere qualcosa stasera?"),
    ("eu e a Tina moramos lá em cima", "io e Tina viviamo al piano di sopra"),
    ("apartamento", "appartamento"),
    ("eu venho", "io vengo"),
    ("obrigado mais uma vez", "hvala ancora"),
    ("está chegando", "sta arrivando"),
    ("vai morar no Brasil por um ano", "in Brasile vivrà un anno"),
    ("ele gosta de música", "gli piace la musica"),
    ("por hobby toca bateria", "per hobby suona la batteria"),
    ("de profissão é físico", "di professione è fisico"),
    ("leiam", "leggete"),
    ("escutem", "ascoltate"),
    ("completem", "completate"),
    ("eu estudo música", "io studio musica"),
    ("o senhor também é músico?", "ste vi anche glasbenik? (siete anche voi un musicista?)"),
    ("também", "anche"),
    ("música", "musica"),
    ("quando ele vê a bateria", "quando vede la batteria"),
    ("logo começa a conversar", "inizia subito a parlare"),
    ("ele começa", "lui inizia"),
    ("começa a conversar", "inizia a parlare (conversare)"),
    ("convida o novo vizinho para beber algo", "invita il nuovo vicino a bere qualcosa"),
    ("convida para beber algo", "lui invita a bere qualcosa"),
    ("convidar", "invitare", WordType.VERB),
    ("ou", "o / oppure"),
    ("como é a sua casa?", "com'è la vostra casa?"),
    ("como é o seu prédio?", "com'è il vostro palazzo?"),
    ("quem são os seus vizinhos?", "chi sono i vostri vicini?"),
    ("como são os seus vizinhos?", "come sono i vostri vicini?"),
    ("eu acho / eu penso", "penso"),
    ("vamos ter um vizinho novo", "avremo un nuovo vicino"),
    ("vizinho", "vicino"),
    ("bateria", "batteria (strumento)"),
    ("perdidos / ignorados", "persi"),
    ("bebida", "bevanda"),
    ("vamos ter / vamos conseguir", ("avremo", "otterremo")),
    ("ele começa", "on začne (lui inizia)"),
    ("vir / chegar", "venire/arrivare", WordType.VERB),

    ("satisfeita", "soddisfatta"),
    ("pequeno", "piccolo"),
    ("satisfeito", "soddisfatto"),
    ("parabéns / felicitações", "congratulazioni"),
    ("um colega de trabalho", "un collega"),
    ("uma colega de trabalho", "una collega"),
    ("os colegas de trabalho", "i colleghi"),
    ("exercícios de texto", "esercizi per i testi"),
)


def run_me():
    dict_pt, dict_ita = process_dictionary(enota)

    number_of_answers = 10

    print("1 - test da portoghese a italiano")
    print("2 - test da italiano a portoghese")
    data = input("risposta (q per uscire): ")
    if data is None or data == "q":
        return
    elif data == "1":
        start_tests(dict_pt, pt2ita=True, number_of_answers=number_of_answers)
    elif data == "2":
        start_tests(dict_ita, pt2ita=False, number_of_answers=number_of_answers)
    else:
        print("risposta non valida")


if __name__ == "__main__":
    run_me()