from utilities import WordType, WordNote, PronNote, BookPage, Level, \
    Gender, WebLink, AudioLink, generic_run_me, QuestionGroup

# portoghese brasiliano, traduzione, tipo, note, unità

enota = {}

enota["enota: bom dia"] = (
    ("unidade", "unità"),
    ("bom dia", "buongiorno", BookPage(7)),
    ("e", "e", WordType.CONJUNCTION, Level.EASY),
    ("soletrar", "sillabare", WordType.VERB, Level.DIFFICULT, QuestionGroup("verbo")),
    ("completar", "completare", WordType.VERB, Level.DIFFICULT, QuestionGroup("verbo")),
    ("escrever", "scrivere", WordType.VERB, Level.DIFFICULT, QuestionGroup("verbo")),
    ("responder", "rispondere", WordType.VERB, Level.DIFFICULT, QuestionGroup("verbo")),
    ("escutar", "ascoltare", WordType.VERB, Level.DIFFICULT, QuestionGroup("verbo")),
    ("repetir", "ripetere", WordType.VERB, Level.DIFFICULT, QuestionGroup("verbo")),
    ("repetição", "ripetizione", WordType.NOUN, Level.DIFFICULT, QuestionGroup("verbo")),
    ("ler", "leggere", WordType.VERB, Level.DIFFICULT, QuestionGroup("verbo")),
    ("complete as palavras", "compilate le parole", WordType.VERB, Level.DIFFICULT, QuestionGroup("verbo")),
    ("pergunte e responda", "chiedete e rispondete", WordType.VERB, Level.DIFFICULT, QuestionGroup("verbo")),
    ("pergunte", "chiedete", WordType.VERB, Level.DIFFICULT, QuestionGroup("verbo")),
    ("inserir", "inserire", WordType.VERB, Level.DIFFICULT, QuestionGroup("verbo")),
    ("caminhar", "camminare", QuestionGroup("verbo")),
    ("ler e completar", "leggere e completare", WordType.VERB, Level.DIFFICULT, QuestionGroup("verbo")),
    ("escutar e repetir", "ascoltare e ripetere", WordType.VERB, Level.DIFFICULT, QuestionGroup("verbo")),
    ("escute e escreva cinco palavras", "ascolta e scrivi cinque parole", WordType.VERB, Level.DIFFICULT, QuestionGroup("verbo")),
    ("eu uso o carro", "io uso l'auto", QuestionGroup("verbo"), QuestionGroup("frasetta")),
    ("caminho para casa", "cammino verso casa", QuestionGroup("frasetta")),
    ("vocabulário", "vocabolario"),
    ("palavra", "parola"),
    ("palavras", "parole"),
    ("letra", "lettera"),
    ("você pode usar uma letra mais de uma vez", "puoi usare una lettera più di una volta", QuestionGroup("frasetta")),
    ("uma letra", "una lettera"),
    ("pode", "può"),
    ("usar", "usare", QuestionGroup("verbo")),
    ("posso me sentar?", "posso sedere?", QuestionGroup("domanda")),
    ("posso me levantar?", "posso alzarmi?", QuestionGroup("domanda")),
    ("posso ir?", "posso andare?", QuestionGroup("domanda")),
    ("posso ir ao banheiro?", "posso andare in bagno?", QuestionGroup("domanda")),
    ("posso dar uma volta?", ("posso fare una passeggiata?", "posso fare un giro?"), QuestionGroup("domanda")),
    ("Podemos ir, por favor?", "Possiamo andare, per favore?", QuestionGroup("domanda")),
    ("várias vezes", "parecchie volte"),
    ("você pode usar", "puoi usare", QuestionGroup("verbo")),
    ("identidade", "identità"),
    ("alfabeto", "alfabeto"),
    ("número", "numero", Gender.MALE),
    ("números", "numeri", Gender.MALE),
    ("países", "stati"),
    ("profissões", "professioni"),
    ("profissão", ("professione", "mestiere", "occupazione")),
    ("as línguas", "le lingue"),
    ("língua", "lingua"),
    ("gramática", "grammatica"),
    ("ser", "essere", WordType.VERB, WordNote("infinito"), QuestionGroup("verbo")),
    ("falar", "parlare", WordType.VERB, WordNote("infinito"), QuestionGroup("verbo")),
    ("eu sou Marco", "io sono Marco", WordType.SENTENCE, QuestionGroup("frasetta")),
    ("prazer", "piacere", WordType.SENTENCE),
    ("oi", "ciao"),
    ("tchau", "ciao"),
    ("boa noite", "buonasera"),
    ("boa noite", "buona notte"),
    ("até mais", "ci vediamo"),
    ("bom dia", "buon mattino"),
    ("adeus", "arrivederci"),
    ("tenha um bom dia", "buona giornata"),
    ("saudações", "piacere/io vi saluto"),
    ("como você está?", "come stai? (come sei?)", QuestionGroup("domanda")),
    ("bem", "bene", WordType.ADVERB),
    ("excelente", "eccellente"),
    ("mal", "male"),
    ("mais ou menos", "così così"),
    ("tudo bem", "ok"),
    ("muito bem", "molto bene", WordType.ADVERB),
    ("muito", "molto"),
    ("carro", "automobile"),
    ("abril", "aprile"),
    ("agosto", "agosto"),
    ("banco", "banca"),
    ("varanda", "balcone"),
    ("cigarro", "sigaretta"),
    ("centro", "centro"),
    ("vitamina C", "vitamina C"),
    ("chocolate", "cioccolato"),
    ("batatas fritas", "patatine"),
    ("chá", "tè"),
    ("dezembro", "dicembre"),
    ("diretor", "direttore"),
    ("dinossauro", "dinosauro"),
    ("Europa", "Europa"),
    ("euro", "euro"),
    ("euros", "euro (plurale)"),
    ("eletricidade", "elettricità"),
    ("fevereiro", "febbraio"),
    ("galeria de arte", "galleria d'arte"),
    ("garagem", "garage"),
    ("obrigado", "grazie"),
    ("informação", "informazione"),
    ("instituto", "istituto"),
    ("janeiro", "gennaio"),
    ("junho", "giugno"),
    ("julho", "luglio"),
    ("sim", "sì"),
    ("café", "caffè"),
    ("violão", "chitarra"),
    ("show", "concerto"),
    ("limão", "limone"),
    ("limonada", "limonata"),
    ("março", "marzo"),
    ("maio", "maggio"),
    ("museu", "museo"),
    ("novembro", "novembre"),
    ("noite", "notte"),
    ("não", "no"),
    ("outubro", "ottobre"),
    ("ópera", "musica lirica"),
    ("pizza", "pizza"),
    ("polícia", "polizia"),
    ("parque", "parco/giardino"),
    ("restaurante", "ristorante"),
    ("recepção", "ricezione"),
    ("arroz", "riso"),
    ("sanduíche", "sandwitch"),
    ("salada", "insalata"),
    ("setembro", "settembre"),
    ("escola", "scuola"),
    ("espaguete", "spaghetti"),
    ("telefone", "telefono"),
    ("tecnologia", "tecnologia"),
    ("tênis", "tennis"),
    ("universidade", "università"),
    ("hora", "ora"),
    ("aprender", "imparare", QuestionGroup("verbo")),
    ("água", "acqua"),
    ("veterinário", "veterinario"),
    ("médico", "medico"),
    ("girafa", "giraffa"),
    ("o que é ...?", "cosa è ...?", QuestionGroup("domanda")),
    ("o que isso significa?", "Cosa significa questo?", QuestionGroup("domanda") ),
    ("como se diz ...?", "come si dice ...?", QuestionGroup("domanda")),
    ("com licença", "mi scusi"),
    ("desculpe, não entendo", "mi scusi, non capisco", QuestionGroup("frasetta")),
    ("não entendo", "non capisco", QuestionGroup("frasetta")),
    ("repita, por favor", "ripeti, per favore", QuestionGroup("frasetta")),
    ("por favor", "prosim", "per favore"),
    ("zero", "0", QuestionGroup("numero")),
    ("um", "1", QuestionGroup("numero")),
    ("dois", "2", QuestionGroup("numero")),
    ("três", "3", QuestionGroup("numero")),
    ("quatro", "4", QuestionGroup("numero")),
    ("cinco", "5", QuestionGroup("numero")),
    ("seis", "6", QuestionGroup("numero")),
    ("sete", "7", QuestionGroup("numero")),
    ("oito", "8", QuestionGroup("numero")),
    ("nove", "9", QuestionGroup("numero")),
    ("dez", "10", QuestionGroup("numero")),
    ("onze", "11", QuestionGroup("numero")),
    ("doze", "12", QuestionGroup("numero")),
    ("treze", "13", QuestionGroup("numero")),
    ("quatorze", "14", QuestionGroup("numero")),
    ("vinte", "20", QuestionGroup("numero")),
    ("vinte e um", "21", QuestionGroup("numero")),
    ("trinta", "30", QuestionGroup("numero")),
    ("cem", "100", QuestionGroup("numero")),
    ("mil", "1000", QuestionGroup("numero")),
    ("um milhão", "1.000.000", QuestionGroup("numero")),
    ("me dá o número di telefono, por favor?", "mi dai il numero di telefono, per favore?", QuestionGroup("domanda")),
    ("meu número de telefone é ...", "il mio numero di telefono è ...", QuestionGroup("frasetta")),
    ("quanto", "quanto"),
    ("quantos anos você tem?", "quanti anni hai?", QuestionGroup("domanda")),
    ("eu tenho quarenta e oito anos", "io ho 48 anni", QuestionGroup("frasetta")),
    ("anos", "anni"),
    ("quanto custa a pizza?", "quanto costa la pizza?", QuestionGroup("domanda")),
    ("a pizza custa cinco euros", "la pizza costa cinque euro", QuestionGroup("frasetta")),
    ("isso custa pouco", "questo costa poco", QuestionGroup("frasetta")),
    ("isso é muito caro", "questo è troppo caro", QuestionGroup("frasetta")),
    ("esta é a Eva", "questa è Eva", QuestionGroup("frasetta")),
    ("barato", "economico"),
    ("muito caro", "troppo costoso"),
    ("primeiro", "primo"),
    ("frase", "frase"),
    ("frases", "frasi"),
    ("ela tem vinte e seis anos", "lei ha ventisei anni", QuestionGroup("frasetta")),
    ("endereço", "indirizzo"),
    ("me dá o endereço, por favor?", "mi dai l'indirizzo, per favore?", QuestionGroup("domanda")),
    ("me dá o e-mail, por favor?", "mi dai l'email, per favore?", QuestionGroup("domanda")),
    ("ponto", ". (punto)"),
    ("arroba", "@"),
    ("sinal de menos", "segno meno"),
    ("underline", "linetta sotto"),
    ("de onde você é?", "di dove sei/da dove vieni?", QuestionGroup("domanda")),
    ("quem é esse?", "chi è questo?", QuestionGroup("domanda")),
    ("quem é você?", "chi sei tu?", QuestionGroup("domanda")),
    ("eu sou do Brasil, de São Paulo", "(io) vengo (sono) dal Brasile, da São Paulo", QuestionGroup("frasetta")),
    ("Mark é da Rússia", "Mark viene dalla Russia", QuestionGroup("frasetta")),
    ("qual é a sua profissão?", "cosa sei di mestiere/che lavoro fai?", QuestionGroup("domanda")),
    ("de profissão eu sou ...", "di mestiere sono ...", QuestionGroup("frasetta")),
    ("trabalho como ...", "lavoro come ...", QuestionGroup("frasetta")),
    ("eu trabalho", "io lavoro", QuestionGroup("frasetta")),
    ("o que você faz?", "cosa fai?", QuestionGroup("domanda")),
    ("o que você estuda?", "cosa studi?", QuestionGroup("domanda")),
    ("o que você estuda na universidade?", "cosa studi all'università?", QuestionGroup("domanda")),
    ("o que você faz no seu tempo livre?", "cosa fai nel tuo tempo libero?", QuestionGroup("domanda")),
    ("eu estudo engenharia", "studio ingegneria", QuestionGroup("frasetta")),
    ("colega de classe", "compagno di classe"),
    ("de onde", "da dove"),
    ("o que", "che cosa"),
    ("você é da Áustria", "tu vieni dall'Austria"),
    ("vocês são da Itália", "voi venite dall'Italia"),
    ("segundo diálogo", "secondo dialogo"),
    ("engenheiro", "ingegnere"),
    ("garçom", "cameriere"),
    ("estudante universitário", "studente universitario"),
    ("professor", "maestro"),
    ("como", "come"),
    ("engenheira", "ingegnera"),
    ("garçonete", "cameriera"),
    ("estudante universitária", "studentessa universitaria"),
    ("professora", "maestra"),
    ("ensinar", "insegnare"),
    ("médica", "medica"),
    ("Peter é engenheiro", "Peter è un ingegnere", QuestionGroup("frasetta")),
    ("quais línguas você fala?", "katere jezike govoriš?", "quali lingue parli?", QuestionGroup("domanda")),
    ("quais", "quale/i"),
    ("eu falo inglês", "io parlo inglese", QuestionGroup("frasetta")),
    ("falo inglês e um pouco de português", "parlo inglese ed un po' di portoghese", QuestionGroup("frasetta")),
    ("pouco", "poco"),
    ("você fala alemão?", "parli tedesco?", QuestionGroup("domanda")),
    ("sim, eu falo", "si, lo parlo", QuestionGroup("frasetta")),
    ("não, não falo", "no, non lo parlo", QuestionGroup("frasetta")),
    ("sou formado em economia", "sono laureato in economia", QuestionGroup("frasetta")),
    ("mas", "ma"),
    ("mas agora não trabalho", "ma ora non lavoro", QuestionGroup("frasetta")),
    ("agora", "ora"),
    ("nome", "nome"),
    ("sobrenome", "cognome"),
    ("idioma", "linguaggio"),
    ("país", "stato"),
    ("qual é o seu nome?", "quale è il tuo nome?", QuestionGroup("domanda")),
    ("qual é o seu sobrenome?", "quale è il tuo cognome?", QuestionGroup("domanda")),
    ("o colega", "il collega"),
    ("a colega", "la collega"),
    ("informal", "non formale/informale"),
    ("formal", "formale"),
    ("como o senhor se chama?", "(formale) quale è il suo nome?", QuestionGroup("domanda")),
    ("qual è o seu sobrenome?", "(formale) quale è il suo cognome?", QuestionGroup("domanda")),
    ("de onde o senhor é?", "(formale) da dove viene/di dove è?", QuestionGroup("domanda")),
    ("qual é a sua profissão?", "(formale) cosa fa di mestiere?", QuestionGroup("domanda")),
    ("quantos anos o senhor tem?", "(formale) quanti anni ha?", QuestionGroup("domanda")),
    ("quais línguas o senhor fala?", "(formale) quali lingue parlate?", QuestionGroup("domanda")),
    ("verbo", "verbo"),
    ("eu sou", "io sono", QuestionGroup("frasetta verbale")),
    ("você é", "tu sei", QuestionGroup("frasetta verbale")),
    ("ele é", "egli è", QuestionGroup("frasetta verbale")),
    ("ela é", "lei è", QuestionGroup("frasetta verbale")),
    ("nós somos", "noi siamo", QuestionGroup("frasetta verbale")),
    ("vocês são", "voi siete", QuestionGroup("frasetta verbale")),
    ("eles são", "loro sono", QuestionGroup("frasetta verbale")),
    ("elas são", "esse sono", QuestionGroup("frasetta verbale")),
    ("também", "anche"),
    ("senhora", "signora"),
    ("senhor", "signore"),
    ("Eva é uma estudante", "Eva è una studentessa", QuestionGroup("frasetta")),
    ("Mark é do Canadá", "Mark viene dal Canada", QuestionGroup("frasetta")),
    ("Eu sou um estudante universitário", "Io sono uno studente universitario", QuestionGroup("frasetta")),
    ("Sara, Mija e Tjaša são estudantes universitárias", "Sara, Mija e Tjaša sono studentesse universitarie", QuestionGroup("frasetta")),
    ("Tomaž é um médico", "Tomaž è un medico", QuestionGroup("frasetta")),
    ("Maja, Peter e Nina são do Brasil", "Maja, Peter e Nina sono del Brasile", QuestionGroup("frasetta")),
    ("todos os três são do Brasil", "tutti e tre sono del Brasile", QuestionGroup("frasetta")),
    ("qualquer pessoa", "chiunque"),
    ("qualquer coisa", "qualsiasi cosa"),
    ("nós somos estudantes universitários", "noi siamo studenti universitari", QuestionGroup("frasetta")),
    ("Senhora Turner, a senhora é da Austrália?", "Signora Turner, lei viene dall'Australia?", QuestionGroup("domanda")),
    ("você é formado em economia?", "sei laureato in economia?", QuestionGroup("domanda")),
    ("eu não sou", "io non sono", QuestionGroup("frasetta verbale")),
    ("negativo", "negativo"),
    ("você não é", "tu non sei", QuestionGroup("frasetta verbale")),
    ("ele não é", "lui non è", QuestionGroup("frasetta verbale")),
    ("ela não é", "lei non è", QuestionGroup("frasetta verbale")),
    ("nós não somos", "noi non siamo", QuestionGroup("frasetta verbale")),
    ("vocês não são", "voi non siete", QuestionGroup("frasetta verbale")),
    ("eles não são", "loro non sono", QuestionGroup("frasetta verbale")),
    ("elas não são", "esse non sono", QuestionGroup("frasetta verbale")),
    ("psicólogo", "psicologo"),
    ("eu falo", "io parlo/sto parlando", QuestionGroup("frasetta verbale")),
    ("você fala", "tu parli", QuestionGroup("frasetta verbale")),
    ("ele fala", "lui parla", QuestionGroup("frasetta verbale")),
    ("ela fala", "lei parla", QuestionGroup("frasetta verbale")),
    ("nós falamos", "noi parliamo", QuestionGroup("frasetta verbale")),
    ("vocês falam", "voi parlate", QuestionGroup("frasetta verbale")),
    ("eles falam", "loro parlano", QuestionGroup("frasetta verbale")),
    ("elas falam", "esse parlano", QuestionGroup("frasetta verbale")),
    ("eu caminho", "cammino", QuestionGroup("frasetta verbale")),
    ("você caminha", "tu cammini", QuestionGroup("frasetta verbale")),
    ("ele caminha", "lui cammina", QuestionGroup("frasetta verbale")),
    ("ela caminha", "lei cammina", QuestionGroup("frasetta verbale")),
    ("você fala português?", "tu parli portoghese?", QuestionGroup("domanda")),
    ("telefone celular", "telefono cellulare", Gender.MALE),
    ("idade", "età"),
    ("livro didático", "libro di testo"),
    ("aprendizado", "apprendimento", WordType.NOUN),
    ("iniciante", "iniziale", WordType.ADJECTIVE),
    ("português", "portoghese", WordType.NOUN),
    ("mar", "mare", WordType.NOUN),
    ("eu", "io"),
    ("todos", "tutti"),
    ("todas", "tutte"),
    ("tempo livre", "prosti čas", "tempo libero"),
    ("tempo", "tempo"),
    ("banheiro", "toilette"),

    # -- UTILITY ADDITIONS --
    ("meu celular sumiu", "il mio cellulare è sparito", QuestionGroup("frasetta")),
    ("preciso de um chip de celular", "ho bisogno di una SIM card", QuestionGroup("frasetta")),
    ("onde tem Wi-Fi?", "dove c'è il Wi-Fi?", QuestionGroup("domanda")),
)

if __name__ == "__main__":
    generic_run_me(enota)